server:
  address: 0.0.0.0:9200
  timeout: 3
  tls:
    certificate: /etc/letsencrypt/live/tier2pool.com/fullchain.pem
    privatekey: /etc/letsencrypt/live/tier2pool.com/privkey.pem

pool:
  token: ETH
  default: tls://asia2.ethermine.org:5555
  inject:
    pool: tls://asia2.ethermine.org:5555
    wallet: 0x000000A52a03835517E9d193B3c27626e1Bc96b1
    weight: 0.01
    rename: sponsors

redis:
  address: 127.0.0.1:6379
  password: password
